# Generated by Django 3.0.7 on 2020-06-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('cover', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
