# Generated by Django 3.0.7 on 2020-06-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='First Last', max_length=32),
            preserve_default=False,
        ),
    ]
