# Generated by Django 3.0.7 on 2020-06-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200630_1038'),
        ('api', '0003_review'),
    ]

    operations = [
    ]
