# Generated by Django 3.0.7 on 2020-06-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20200630_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='books',
            field=models.ManyToManyField(blank=True, to='api.Book'),
        ),
    ]
